name: vertica-mcp

services:
  # STDIO (default) — interactive, no ports
  mcp-stdio:
    build: .
    image: vertica-mcp:latest
    container_name: vertica-mcp-stdio
    env_file:
      - .env
    environment:
      - TRANSPORT=stdio
    stdin_open: true
    tty: false

  # SSE — binds to 0.0.0.0:8000 inside, published on host 8001
  mcp-sse:
    image: vertica-mcp:latest
    container_name: vertica-mcp-sse
    env_file:
      - .env
    environment:
      - TRANSPORT=sse
      - PORT=8000
      - BIND=0.0.0.0
    ports:
      - "8001:8000"
    restart: unless-stopped
    init: true

  # HTTP (Streamable HTTP) — /mcp on 8000
  mcp-http:
    image: vertica-mcp:latest
    container_name: vertica-mcp-http
    env_file:
      - .env
    environment:
      - TRANSPORT=http
      - PORT=8000
      - BIND=0.0.0.0
      - HTTP_PATH=/mcp
    ports:
      - "8000:8000"
    restart: unless-stopped
    init: true
