services:
  mcp-stdio:
    build: .
    image: vertica-mcp:latest
    container_name: vertica-mcp-stdio
    environment:
      - TRANSPORT=${TRANSPORT:-stdio}
      - PORT=${PORT:-8000}
    stdin_open: true
    tty: false
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]

  mcp-http:
    build: .
    image: vertica-mcp:latest
    container_name: vertica-mcp-http
    environment:
      - TRANSPORT=${TRANSPORT:-http}
      - BIND=${BIND:-0.0.0.0}
      - PORT=${PORT:-8000}
      - HTTP_PATH=${HTTP_PATH:-/mcp}
    ports:
      - "${HTTP_HOST_PORT:-8000}:${PORT:-8000}"
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]

  mcp-sse:
    build: .
    image: vertica-mcp:latest
    container_name: vertica-mcp-sse
    environment:
      - TRANSPORT=${TRANSPORT:-sse}
      - BIND=${BIND:-0.0.0.0}
      - PORT=${PORT:-8000}
    ports:
      - "${SSE_HOST_PORT:-8001}:${PORT:-8000}"
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
