[project]
name = "vertica-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
    "mcp[cli]>=1.12.0",
    "python-dotenv>=1.1.1",
    "vertica-python>=1.4.0",
]
